const menuList=[
    {
        key:'/home',
        icon:'pie-chart',
        name:'首页'
    },
    {
        key:'/products',
        icon:'pie-chart',
        name:'商品',
        children:[
            {
                key:'/products/category',
                icon:'pie-chart',
                name:'品类管理'
            },
            {
                key:'/products/product',
                icon:'pie-chart',
                name:'商品管理'
            }
        ]
    },
    {
        key:'/user',
        icon:'pie-chart',
        name:'用户管理'
    },
    {
        key:'/role',
        icon:'pie-chart',
        name:'角色管理'
    },
    {
        key:'/echarts',
        icon:'pie-chart',
        name:'图形图表',
        children:[
            {
                key:'/echarts/bar',
                icon:'pie-chart',
                name:'柱形图'
            },
            {
                key:'/echarts/line',
                icon:'pie-chart',
                name:'折线图'
            },
            {
                key:'/echarts/pie',
                icon:'pie-chart',
                name:'饼图'
            }
        ]
    }
]
export default menuList